### ISSUE TITLE
Swiperjs video support

### ISSUE THREAD

**Issue by xl3ehindTim** [xl3ehindTim/delta-site#24]
The swiper dragging does not function as expected with HTML5 video elements. 
Expected result is that when you drag the swiper horizontally scrolls which is the expected usage.

https://github.com/xl3ehindTim/delta-site/assets/32740573/c6745cf9-aaab-435a-9662-949d6658207c

**Comment by xl3ehindTim** [comment]
This issue occurs because of video 'controls'

**Comment by ScriptDeBurger** [comment]
Double it and pass it to the next person
